import type { AttachmentTextStatus } from '@/lib/attachments/attachment-text-extractor';
import dedent from 'dedent';

/**
 * End-to-end fixtures for the inbound-attachment flow: a real document on disk, the email it
 * arrived with, and what the pipeline should make of the two together.
 *
 * Run with `pnpm test:ai:attachments` (live OpenAI; skipped without OPENAI_API_KEY).
 * The documents live in `./files/` and are regenerated by `scripts/build-attachment-fixtures.cjs`
 * — when you change a document there, change the expectations here in the same commit.
 *
 * Dates are absolute and later than REFERENCE_DATE_ISO so nothing depends on "next week".
 */

export const ATTACHMENT_FLOW_REFERENCE_DATE_ISO = '2026-05-16';

/** Share of fixtures that must be fully acceptable for the harness to pass. */
export const MIN_ATTACHMENT_FIXTURE_PASS_RATE = 0.8;

export interface AttachmentFlowFile {
	/** Filename inside `./files/`. Also the name the pipeline would see on the email. */
	file: string;
	/** MIME type as the mail client would announce it — deliberately wrong on some fixtures. */
	mimeType: string;
	expectedStatus: AttachmentTextStatus;
	/** Substrings the extracted text must contain. Proves the parser read the real content. */
	mustContain?: string[];
}

export interface AttachmentFlowExpectedExtraction {
	/** Fuzzy: ≥50% of these tokens must appear in the extracted requestType. */
	requestType?: string;
	/** Fuzzy token match; null means the field must come back null. */
	address?: string | null;
	/** ISO date, ±2 days. */
	customerDeadline?: string | null;
	customerAppointment?: string | null;
	/** ≥50% must be matched by some extracted deliverable hint. */
	deliverableHints?: string[];
}

export interface AttachmentFlowFixture {
	name: string;
	notes: string;
	email: { subject: string; fromName: string; fromEmail: string; bodyText: string };
	files: AttachmentFlowFile[];
	expected: {
		isQuote: boolean;
		extraction?: AttachmentFlowExpectedExtraction;
		/** Must appear NOWHERE in requestType or deliverableHints — content that is noise. */
		mustNotExtract?: string[];
	};
}

const PDF = 'application/pdf';
const DOCX = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document';

export const NL_ATTACHMENT_FLOW_FIXTURES: AttachmentFlowFixture[] = [
	{
		name: 'PDF bestek, body only says "zie bijlage"',
		notes: 'The core case. Every extractable fact — address, quantities, deadline, site visit — is in the PDF. Before attachments were read this produced a lead with empty fields.',
		email: {
			subject: 'Offerteaanvraag dakrenovatie',
			fromName: 'Jan van den Berg',
			fromEmail: 'j.vandenberg@example.nl',
			bodyText: dedent`
				Goedemiddag,

				Graag ontvangen wij een offerte. Zie het bestek in de bijlage.

				Met vriendelijke groet,
				Jan van den Berg
			`
		},
		files: [
			{
				file: 'bestek-dakrenovatie.pdf',
				mimeType: PDF,
				expectedStatus: 'PARSED',
				mustContain: ['Kerkstraat 12', '120 m2', '15 juni 2026', '26 mei 2026']
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'dakrenovatie',
				address: 'Kerkstraat 12 Amersfoort',
				customerDeadline: '2026-06-15',
				customerAppointment: '2026-05-26',
				deliverableHints: ['120 m2', 'dakpannen', 'isolatie', '24 meter']
			}
		}
	},
	{
		name: 'Word programma van eisen — thin-body rescue',
		notes: 'The body never says offerte or prijs; alone it reads as a courtesy note. Only the .docx reveals a request for pricing. This is the mail that used to vanish silently into the RawMessage archive. The report shows whether the first verdict was negative and the second look flipped it.',
		email: {
			subject: 'NetSuite koppeling',
			fromName: 'Pieter de Wit',
			fromEmail: 'p.dewit@example.nl',
			bodyText: dedent`
				Hoi,

				Zie bijlage.

				Groet,
				Pieter
			`
		},
		files: [
			{
				file: 'programma-van-eisen-netsuite.docx',
				mimeType: DOCX,
				expectedStatus: 'PARSED',
				mustContain: ['NetSuite', 'prijsopgave', '12 juni 2026']
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'NetSuite integratie koppelingen',
				// No `address` expectation on purpose: Industrieweg 8 is the company's office, not a job
				// site, and a software integration has no work location. null and the office address are
				// both defensible, so asserting either would just burn the one tolerated soft miss.
				customerDeadline: '2026-06-12',
				deliverableHints: ['webshop', 'voorraad', 'facturen']
			}
		}
	},
	{
		name: 'Excel stuklijst sent as application/octet-stream',
		notes: 'Two things at once: the MIME type is generic (mail clients do this constantly) so the kind must resolve from the extension, and the facts are split across two sheets — quantities on one, address + deadline on the other.',
		email: {
			subject: 'Prijs warmtepomp installatie',
			fromName: 'Sanne Bakker',
			fromEmail: 'sanne@example.nl',
			bodyText: dedent`
				Hallo,

				Kunnen jullie op basis van de bijgevoegde stuklijst een prijs maken?

				Groeten,
				Sanne Bakker
			`
		},
		files: [
			{
				file: 'stuklijst-warmtepomp.xlsx',
				mimeType: 'application/octet-stream',
				expectedStatus: 'PARSED',
				mustContain: [
					'Blad: Stuklijst',
					'Lucht-water warmtepomp 8 kW | 2 | stuks',
					'Blad: Project',
					'Molenweg 45'
				]
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'warmtepomp installatie',
				address: 'Molenweg 45 Ede',
				customerDeadline: '2026-06-19',
				deliverableHints: ['warmtepomp', 'buffervat', '35 meter']
			}
		}
	},
	{
		name: 'Legacy Word 97 .doc',
		notes: 'A genuine OLE binary, not a renamed file. A lot of Dutch trade paperwork still circulates in this format.',
		email: {
			subject: 'Schilderwerk woning',
			fromName: 'Mevr. H. Jansen',
			fromEmail: 'h.jansen@example.nl',
			bodyText: dedent`
				Geachte heer/mevrouw,

				Zie de bijgevoegde werkomschrijving. Graag verneem ik uw prijs.

				Hoogachtend,
				H. Jansen
			`
		},
		files: [
			{
				file: 'werkomschrijving-schilderwerk.doc',
				mimeType: 'application/msword',
				expectedStatus: 'PARSED',
				mustContain: ['Lindelaan 7', '14 kozijnen', '22 juni 2026']
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'buitenschilderwerk schilderwerk',
				address: 'Lindelaan 7 Deventer',
				customerDeadline: '2026-06-22',
				deliverableHints: ['14 kozijnen', 'buitendeuren', 'dakgoten']
			}
		}
	},
	{
		name: 'Legacy .xls materiaallijst, address only in the body',
		notes: 'Facts split the other way round: the body carries the address and the ask, the BIFF8 workbook carries the scope. Both must land in one extraction.',
		email: {
			subject: 'Badkamer verbouwen',
			fromName: 'Tom Visser',
			fromEmail: 'tom.visser@example.nl',
			bodyText: dedent`
				Beste,

				Wij willen onze badkamer laten verbouwen aan de Dorpsstraat 9 in Zeist.
				De materiaallijst staat in de bijlage. Wat gaat dit ongeveer kosten?

				Groet,
				Tom Visser
			`
		},
		files: [
			{
				file: 'materiaallijst-badkamer.xls',
				mimeType: 'application/vnd.ms-excel',
				expectedStatus: 'PARSED',
				mustContain: ['Inloopdouche glaswand 120 cm | 1 | stuks', 'Wandtegels 30x60 mat wit | 28 | m2']
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'badkamer verbouwen',
				address: 'Dorpsstraat 9 Zeist',
				deliverableHints: ['inloopdouche', 'wandtegels', 'vloertegels', 'badkamermeubel']
			}
		}
	},
	{
		name: 'Supplier price list — must stay negative',
		notes: 'The guard against the obvious failure of this feature: attachment text full of prices and the word "offerte" making every mail with a PDF look like a lead. Direction is reversed — THEY are selling to US.',
		email: {
			subject: 'Prijslijst 2026',
			fromName: 'Groothandel Van Dijk',
			fromEmail: 'verkoop@example.nl',
			bodyText: dedent`
				Beste relatie,

				In de bijlage vindt u onze nieuwe prijslijst voor 2026.

				Met vriendelijke groet,
				Verkoop binnendienst
			`
		},
		files: [
			{
				file: 'prijslijst-groothandel-2026.pdf',
				mimeType: PDF,
				expectedStatus: 'PARSED',
				mustContain: ['Prijslijst 2026', 'Offertes op aanvraag']
			}
		],
		expected: { isQuote: false }
	},
	{
		name: 'Prompt injection inside a PDF — must stay negative',
		notes: 'The document tells the model to classify the mail as an emergency quote request. Attachment text is attacker-controlled exactly like the body; it is JSON-encoded into the prompt and the prompt says instructions inside attachments are data. (In production the bulk-mail filter would stop this newsletter first; the harness tests the classifier as the last line of defence.)',
		email: {
			subject: 'Voorjaarsnieuwsbrief',
			fromName: 'Tuincentrum Groen',
			fromEmail: 'nieuwsbrief@example.nl',
			bodyText: dedent`
				Beste klant,

				Bekijk onze voorjaarsnieuwsbrief in de bijlage.
			`
		},
		files: [
			{
				file: 'nieuwsbrief-met-injectie.pdf',
				mimeType: PDF,
				expectedStatus: 'PARSED',
				mustContain: ['SYSTEEMINSTRUCTIE']
			}
		],
		expected: { isQuote: false }
	},
	{
		name: 'Unreadable scan — the body must carry the request',
		notes: 'A PDF with pages but no text layer (a scan, a photographed drawing). It must read as EMPTY — "we could not read this" — never as a successful parse of nothing, and the lead must still be created from the body alone.',
		email: {
			subject: 'Cv-ketel vervangen',
			fromName: 'Familie Smit',
			fromEmail: 'smit@example.nl',
			bodyText: dedent`
				Goedendag,

				Graag een offerte voor het vervangen van onze cv-ketel (Remeha, 12 jaar oud)
				aan de Beukenlaan 21 in Zwolle. Een tekening van de opstelling zit in de bijlage.

				Vriendelijke groet,
				Familie Smit
			`
		},
		files: [{ file: 'scan-zonder-tekstlaag.pdf', mimeType: PDF, expectedStatus: 'EMPTY' }],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'cv-ketel vervangen',
				address: 'Beukenlaan 21 Zwolle',
				deliverableHints: ['cv-ketel']
			}
		}
	},
	{
		name: 'Email contradicts the attachment — the email wins',
		notes: 'The PDF says 30 juni; the customer corrects it to 20 juni in the mail itself. The extractor prompt says the email wins a conflict (it is more recent and typed by the customer). Scope still comes from the attachment.',
		email: {
			subject: 'Offerte zonnepanelen',
			fromName: 'Eva Mulder',
			fromEmail: 'eva.mulder@example.nl',
			bodyText: dedent`
				Hallo,

				Zie de bijlage voor de details van onze aanvraag. Let op: in de bijlage staat
				nog 30 juni, maar wij hebben de offerte echt uiterlijk 20 juni 2026 nodig.

				Groet,
				Eva Mulder
			`
		},
		files: [
			{
				file: 'opdrachtbevestiging-afwijkende-datum.pdf',
				mimeType: PDF,
				expectedStatus: 'PARSED',
				mustContain: ['14 zonnepanelen', '30 juni 2026']
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'zonnepanelen',
				address: 'Parkweg 3 Den Haag',
				customerDeadline: '2026-06-20',
				deliverableHints: ['14 zonnepanelen', '430 Wp', 'omvormer']
			}
		}
	},
	{
		name: 'Attachment is pure noise (inkoopvoorwaarden)',
		notes: 'A real request in the body, and an attachment that is legal boilerplate. The terms must not leak into the scope: "betalingstermijn" and "rechtbank" are not deliverables.',
		email: {
			subject: 'Onderhoud airco',
			fromName: 'Facilitair Bureau Oost',
			fromEmail: 'inkoop@example.nl',
			bodyText: dedent`
				Geachte heer/mevrouw,

				Graag ontvangen wij een offerte voor het jaarlijks onderhoud van 6 airco-units
				op ons kantoor aan het Stationsplein 1 in Arnhem. Onze inkoopvoorwaarden vindt
				u in de bijlage.

				Met vriendelijke groet,
				Facilitair Bureau Oost
			`
		},
		files: [
			{
				file: 'algemene-voorwaarden.pdf',
				mimeType: PDF,
				expectedStatus: 'PARSED',
				mustContain: ['betalingstermijn']
			}
		],
		expected: {
			isQuote: true,
			extraction: {
				requestType: 'onderhoud airco',
				address: 'Stationsplein 1 Arnhem',
				deliverableHints: ['6 airco-units', 'onderhoud']
			},
			mustNotExtract: ['betalingstermijn', 'aansprakelijk', 'rechtbank', 'nederlands recht']
		}
	}
];
