-- CreateEnum
CREATE TYPE "Vertical" AS ENUM ('LOODGIETER', 'ELEKTRICIEN', 'SCHILDER', 'TIMMERMAN', 'DAKDEKKER', 'TEGELZETTER', 'HOVENIER', 'INSTALLATEUR', 'SCHOONMAAK', 'OVERIG');

-- AlterTable
ALTER TABLE "Organization" ADD COLUMN     "vertical" "Vertical" NOT NULL DEFAULT 'OVERIG';
